<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class AchievementsTableSeeder extends Seeder
{
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        DB::table('achievements')->truncate();
        Schema::enableForeignKeyConstraints();

        DB::unprepared(<<<SQL
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0001', 'ATH0010', 'Liga Pelajar Nasional 2024', 'national', 'Kemenpora', 'Jakarta, Indonesia', '2024-08-12', '2024-08-18', 'Juara 1 Liga Pelajar Indonesia U-17', 'Turnamen 16 tim putra', 'mencetak 4 gol dan 2 assist selama turnamen.', NULL, 'gold', 1, 'Final: 3 – 1 ', '2025-11-29 22:31:07', '2025-11-29 23:01:04');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0002', 'ATH0010', 'Kejuaraan Wilayah Sepak Bola Jawa Barat 2023', 'city_regional_club', 'Asprov PSSI Jabar', 'Bandung, Indonesia', '2023-06-03', '2023-06-07', 'Peringkat 2 Turnamen Antar Sekolah Jawa Barat', 'Turnamen 16 tim putra', 'mencetak 5 gol dalam keseluruhan turnamen.', NULL, 'silver', 2, 'Final: 0 – 1', '2025-11-29 22:32:24', '2025-11-29 23:01:58');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0003', 'ATH0010', 'Friendly Cup Antar Klub 2022', 'city_regional_club', 'Klub Persada Muda', 'Bogor, Indonesia', '2022-11-10', '0022-11-12', 'Peringkat 5 Friendly Cup U-18', 'Turnamen 16 tim putra', 'Pemain mencetak 1 gol di pertandingan perebutan peringkat 3.', NULL, 'non_podium', 5, 'Kalah 1–2', '2025-11-29 22:33:41', '2025-11-29 23:06:27');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0004', 'ATH0009', 'Kejuaraan Panahan Nasional Junior', 'national', 'Perpani', 'Jakarta, Indonesia', '2024-08-05', '2024-08-05', 'Juara 1 Babak Kualifikasi', 'Putra Perorangan – Olympic Round 70m', 'Konsisten dengan rata-rata skor tinggi di seluruh end.', NULL, 'gold', 1, '652 poin (70m)', '2025-11-29 22:40:16', '2025-11-29 22:40:16');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0005', 'ATH0009', 'Turnamen Panahan Pelajar se-Jawa Barat', 'city_regional_club', 'Dispora Jawa Barat', 'Bandung, Indonesia', '2023-10-14', '2023-10-16', 'Runner Up Eliminasi Beregu', 'Putra Beregu – Olympic Round 70m', 'Kekalahan tipis pada babak final.', NULL, 'silver', 2, 'Set Score Final 4–5', '2025-11-29 22:41:29', '2025-11-29 22:41:29');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0006', 'ATH0009', 'Junior Archery Friendly Series', 'city_regional_club', 'Perpani Cimahi', 'Cimahi, Indonesia', '2025-01-21', '2025-01-21', 'Juara 3 Babak Kualifikasi Mixed Team', 'Campuran Beregu (Mixed Team)', 'Finishing strong dan berhasil mengamankan posisi podium.', NULL, 'bronze', 3, '1240 poin (akumulasi tim)', '2025-11-29 22:43:11', '2025-11-29 22:43:11');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0007', 'ATH0008', 'Liga Siswa Nasional', 'city_regional_club', 'Kemenpora', 'Surabaya, Indonesia', '2004-10-03', '2024-06-10', 'Peringkat 2 Liga Siswa Nasional', 'Bola basket putra', 'Pemain mencetak total 68 poin sepanjang turnamen (rata-rata 11–14 PPG).', NULL, 'silver', 2, 'Final Score 54–62', '2025-11-29 22:53:44', '2025-11-29 22:53:44');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0008', 'ATH0008', 'Bandung School 3x3 Championship', 'city_regional_club', 'Dispora Kota Bandung', 'Bandung, Indonesia', '2023-11-19', '2023-11-20', 'Juara 1 Kejuaraan 3x3 Antar Sekolah', '3x3 putra', 'Mencetak 9 poin di final dan total 34 poin selama turnamen.', NULL, 'gold', 1, '12–9 (Final)', '2025-11-29 22:55:26', '2025-11-29 22:55:26');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0009', 'ATH0008', 'Youth Basketball Invitational Cup', 'city_regional_club', 'PBS Cimahi', 'Cimahi, Indonesia', '2025-02-05', '2025-02-05', 'Peringkat 4 Youth Invitational Cup', 'Bola basket putrav', 'Mencetak 21 poin pada laga perebutan posisi 3–4.', NULL, 'non_podium', 4, 'Kalah 48-52 (Q4)', '2025-11-29 22:59:29', '2025-11-29 22:59:29');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0010', 'ATH0007', 'Kejuaraan Nasional eFootball Indonesia', 'national', 'Jakarta, Indonesia', 'IESPA (Indonesia eSport Association)', '2024-05-10', '2024-05-12', 'Peringkat 3 Kejuaraan Nasional eFootball', 'Pro Evolution Soccer (PES / eFootball)', 'Pemain memenangkan 5 dari 7 pertandingan, mencetak total 18 gol dalam turnamen.', NULL, 'bronze', 3, 'Kalah 1–3 di semifinal', '2025-11-29 23:08:39', '2025-11-29 23:08:39');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0011', 'ATH0007', 'West Java eSport Championship', 'city_regional_club', 'Dispora Jawa Barat, IESPA Jabar', 'Bandung, Indonesia', '2023-11-04', '2023-11-06', 'Juara 1 Turnamen League of Legends Jawa Barat', 'League of Legends', 'Bermain sebagai Midlaner, mencatat KDA 12.4 sepanjang semifinal hingga final.', NULL, 'gold', 1, 'Menang 3–0 (Best of Five)', '2025-11-29 23:10:30', '2025-11-29 23:10:30');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0012', 'ATH0007', 'AoV City Cup Cimahi', 'city_regional_club', 'Komunitas eSport Cimahi (CEC)', 'Cimahi, Indonesia', '2025-01-21', '2025-01-21', 'Peringkat 2 Arena of Valor City Cup', 'Arena of Valor (AoV)', 'Menggunakan hero Mage, mencatat total 47 kill sepanjang turnamen.', NULL, 'silver', 2, 'Final Score 1–2 (Best of Three)', '2025-11-29 23:11:51', '2025-11-29 23:11:51');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0013', 'ATH0006', 'ASEAN Women’s 3x3 Challenge', 'international', 'FIBA Asia', 'Kuala Lumpur, Malaysia', '2024-08-10', '2024-08-12', 'Peringkat 5 ASEAN Women’s 3x3 Challenge', '3x3 putri', 'Mencetak 22 poin selama turnamen (tertinggi 9 poin vs Thailand).', NULL, 'non_podium', 5, 'Kalah 11–15 (Quarterfinal)', '2025-11-29 23:17:03', '2025-11-29 23:17:03');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0014', 'ATH0006', 'Women’s National Basketball Open', 'national', 'Perbasi Pusat', 'Yogyakarta, Indonesia', '2024-07-02', '2024-07-09', 'Peringkat 1 Women’s National Basketball Open', 'Bola basket putri', 'Mencetak 72 poin sepanjang turnamen (21 poin di final).', NULL, 'gold', 1, 'Menang 61–48', '2025-11-29 23:18:27', '2025-11-29 23:18:37');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0015', 'ATH0006', 'West Java Women’s 3x3 Series', 'city_regional_club', 'Perbasi Jawa Barat', 'Bandung, Indonesia', '2023-11-18', '2023-11-19', 'Peringkat 6 West Java Women’s 3x3 Series', '3x3 putri', 'Mencetak 14 poin total.', NULL, 'non_podium', 6, 'Kalah 7–12 (QF)', '2025-11-29 23:19:45', '2025-11-29 23:19:45');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0016', 'ATH0005', 'Asian Pacific Women’s Sabre Open', 'international', 'FIE Asia', 'Seoul, Korea Selatan', '2024-06-12', '2024-06-14', 'Peringkat 7 Asian Pacific Women’s Sabre Open', 'Sabre Perorangan (Women)', 'Menang 3 dari 6 duel di babak pool.\nPoin indikator total: +8', NULL, 'non_podium', 7, 'Gugur di Top 8 (15–12)', '2025-11-29 23:22:57', '2025-11-29 23:22:57');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0017', 'ATH0005', 'Southeast Asia Fencing Series', 'continental', 'SEAFF (SEA Fencing Federation)', 'Kuala Lumpur, Malaysia', '2024-02-03', '2024-02-05', 'Juara 3 Southeast Asia Fencing Series', 'Foil Perorangan (Women)', 'Total touch scored: 37,\nBest bout: menang 15–7 di Quarterfinal', NULL, 'bronze', 3, 'Kalah 9–15 di semifinal', '2025-11-29 23:24:27', '2025-11-29 23:24:27');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0018', 'ATH0005', 'Kejuaraan Nasional Anggar Putri', 'national', 'IKASI (Persatuan Anggar Indonesia)', 'Jakarta, Indonesia', '2024-09-20', '2024-09-24', 'Juara 1 Kejurnas Anggar Putri', 'Epee Perorangan (Women)', 'Statistik final: kemenangan 15–10,\nTouch total sepanjang turnamen: 64', NULL, 'gold', 1, 'Menang 15–10 (Final)', '2025-11-29 23:25:57', '2025-11-29 23:25:57');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0019', 'ATH0004', 'Women’s Flyweight International Open', 'international', 'IFMA International', 'Bangkok, Thailand', '2024-06-15', '2024-06-17', 'Peringkat 4 Women’s Flyweight International Open', 'Flyweight 48–51 kg (Women)', 'Menang 2 laga, kalah di perebutan peringkat 3. \nTotal strike landed: 67. \nBest round: R2 (20 clean shots).', NULL, 'non_podium', 4, 'Kalah 28–30 (Juri)', '2025-11-29 23:29:12', '2025-11-29 23:29:12');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0020', 'ATH0004', 'Southeast Asia Muay Thai Series', 'continental', 'SEAMF', 'Kuala Lumpur, Malaysia', '2024-03-08', '2024-03-10', 'Juara 3 Southeast Asia Muay Thai Series', 'Flyweight 48–51 kg (Women)', 'Knockdown sekali di Quarterfinal.\nTotal poin turnamen: 84.', NULL, 'bronze', 3, 'Kalah semifinal 27–30', '2025-11-29 23:30:29', '2025-11-29 23:30:29');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0021', 'ATH0004', 'Kejuaraan Nasional Muay Thai Putri', 'national', 'PB Muay Thai Indonesia', 'Jakarta, Indonesia', '2024-10-21', '2024-10-24', 'Juara 1 Kejurnas Muay Thai Indonesia', 'Flyweight 48–51 kg (Women)', 'Chepi menang TKO Ronde 3 di final.\nTotal significant strikes: 95.', NULL, 'gold', 1, 'TKO R3', '2025-11-29 23:31:44', '2025-11-29 23:31:44');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0022', 'ATH0004', 'West Java Muay Thai Open', 'city_regional_club', 'Muay Thai Jawa Barat', 'Bandung, Indonesia', '2025-04-07', '2025-04-07', 'Peringkat 5 West Java Muay Thai Open', 'Flyweight 48–51 kg (Women)', 'Strike accuracy: 61%. \nGugur di Top 8.', NULL, 'non_podium', 5, 'Kalah 29–30', '2025-11-29 23:32:52', '2025-11-29 23:32:52');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0023', 'ATH0004', 'Cimahi Women’s Muay Thai Cup', 'city_regional_club', 'Cimahi Combat Sports Club', 'Cimahi, Indonesia', '2024-02-12', '2024-02-12', 'Runner Up Cimahi Women’s Muay Thai Cup', 'Flyweight 48–51 kg (Women)', 'Final: Kalah split decision 28–29\n3 clinch control attempt sukses.', NULL, 'silver', 2, 'Kalah 28–29 (Split Decision)', '2025-11-29 23:33:56', '2025-11-29 23:33:56');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0024', 'ATH0003', 'World University Pencak Silat Championships', 'international', 'IPSF', 'Bangkok, Thailand', '2024-05-16', '2024-05-18', 'Peringkat 5 World University Pencak Silat Championships', 'Tanding Putri 50–55 kg', 'Menang 1 laga, kalah di Top 8.\nPoin total: 42–46 selama turnamen.', NULL, 'non_podium', 5, 'Kalah 1–2 (Juri)', '2025-11-29 23:37:23', '2025-11-29 23:37:23');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0025', 'ATH0003', 'Southeast Asia Silat Challenge', 'continental', 'SEAPS', 'Kuala Lumpur, Malaysia', '2024-02-09', '2024-02-11', 'Juara 2 Southeast Asia Silat Challenge', 'Tanding Putri 50–55 kg', 'Total 3 poin unggul di semifinal.\nFinal kalah tipis: 39–40.', NULL, 'silver', 2, 'Kalah 39–40 (Final)', '2025-11-29 23:38:26', '2025-11-29 23:38:26');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0026', 'ATH0003', 'Kejuaraan Nasional Silat Putri', 'national', 'IPSI', 'Surabaya, Indonesia', '2024-09-21', '2024-09-25', 'Juara 1 Kejurnas Pencak Silat Indonesia', 'Tanding Putri 50–55 kg', 'Final menang 3–0 juri.\nTotal poin selama turnamen: 57.', NULL, 'gold', 1, 'Menang 3–0 (Juri)', '2025-11-29 23:39:51', '2025-11-29 23:39:51');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0027', 'ATH0003', 'West Java Silat Open', 'city_regional_club', 'IPSI Jawa Barat', 'Bandung, Indonesia', '2025-03-12', '2025-03-12', 'Peringkat 4 West Java Silat Open', 'Tanding Putri 50–55 kg', 'Total poin: 31–35\nGugur di perebutan peringkat 3.', NULL, 'non_podium', 4, 'Kalah 1–2 Juri (Bronze Fight)', '2025-11-29 23:40:59', '2025-11-29 23:40:59');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0028', 'ATH0003', 'Cimahi Women’s Silat Cup', 'city_regional_club', 'UKM Pencak Silat Cimahi', 'Cimahi, Indonesia', '2024-01-10', '2024-01-10', 'Juara 3 Cimahi Women’s Silat Cup', 'Tanding Putri 50–55 kg', 'Menang 2 kali, kalah 1 kali.\nPoin terbaik: 12–6 pada penyisihan grup.', NULL, 'bronze', 3, 'Menang 2–1 Juri (Perebutan posisi 3)', '2025-11-29 23:42:07', '2025-11-29 23:42:07');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0029', 'ATH0002', 'Asian Equestrian Grand Prix', 'international', 'FEI Asia', 'Seoul, Korea Selatan', '2024-06-07', '2024-06-09', 'Peringkat 8 Asian Equestrian Grand Prix – Jumping', 'Individual Jumping', 'Cleared 11 dari 12 obstacle, 1 time penalty.\nWaktu: 74.98 detik', NULL, 'non_podium', 8, 'Penalti total 5', '2025-11-29 23:44:38', '2025-11-29 23:44:38');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0030', 'ATH0002', 'Southeast Asia Dressage Invitational', 'continental', 'SEACF (SEA Equestrian Federation)', 'Kuala Lumpur, Malaysia', '2024-03-12', '2024-03-13', 'Juara 3 Southeast Asia Dressage Invitational', 'Individual Dressage', 'Skor rata-rata juri: 71.2%. \nHighlight: konsisten pada extended trot & canter transition.', NULL, 'bronze', 3, 'Skor akhir 71.2%', '2025-11-29 23:45:50', '2025-11-29 23:45:50');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0031', 'ATH0002', 'Kejuaraan Nasional Equestrian Indonesia', 'national', 'PORDASI & PP Equestrian', 'Jakarta, Indonesia', '2024-10-18', '2024-10-20', 'Juara 1 Kejurnas Berkuda Indonesia – Dressage', 'Individual Dressage', 'Skor final: 74.6%. \nMendapat nilai tertinggi pada freestyle routine.', NULL, 'gold', 1, 'Skor 74.6%', '2025-11-29 23:47:00', '2025-11-29 23:47:00');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0032', 'ATH0002', 'West Java Horse Jumping Open', 'city_regional_club', 'PORDASI Jawa Barat', 'Bandung, Indonesia', '2025-02-05', '2025-02-05', 'Peringkat 6 West Java Horse Jumping Open', 'Individual Jumping', 'Penalti: 12 (dua knockdown, satu refusal). \nWaktu: 82.14 detik.', NULL, 'non_podium', 6, '12', '2025-11-29 23:48:10', '2025-11-29 23:48:10');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0033', 'ATH0002', 'Cimahi Equestrian Club Cup', 'city_regional_club', 'Cimahi Riding Club', 'Cimahi, Indonesia', '2024-01-14', '2024-01-14', 'Runner Up Cimahi Equestrian Club Cup', 'Individual Jumping', 'Waktu cepat: 70.32 detik, satu knockdown.', NULL, 'silver', 2, 'Penalti 4', '2025-11-29 23:49:09', '2025-11-29 23:49:09');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0034', 'ATH0001', 'Asian Women’s Table Tennis Open', 'international', 'ATTU (Asian Table Tennis Union)', 'Bangkok, Thailand', '2024-06-12', '2024-06-14', 'Peringkat 5 Asian Women’s Table Tennis Open', 'Perorangan Putri', 'Total kemenangan: 4 dari 6 pertandingan.\nSkor tertinggi: 11–4, 11–6, 11–7 vs Thailand.', NULL, 'non_podium', 5, 'Gugur di Quarterfinal (2–4 set)', '2025-11-29 23:52:08', '2025-11-29 23:52:08');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0035', 'ATH0001', 'Southeast Asia Mixed Doubles Challenge', 'continental', 'SEATTF', 'Kuala Lumpur, Malaysia', '2024-03-08', '2024-03-10', 'Juara 2 Southeast Asia Mixed Doubles Challenge', 'Ganda Campuran', 'Total rally terpanjang: 28 pukulan. \nMenang semifinal dengan skor 3–1.', NULL, 'silver', 2, 'Kalah final 2–3', '2025-11-29 23:53:16', '2025-11-29 23:53:16');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0036', 'ATH0001', 'Kejuaraan Nasional Tenis Meja Indonesia', 'national', 'PTMSI', 'Surabaya, Indonesia', '2024-09-20', '2024-09-23', 'Juara 1 Kejurnas Tenis Meja Indonesia – Perorangan Putri', 'Perorangan Putri', 'Final menang telak 4–0 set. \nPersentase serve success: 83%', NULL, 'gold', 1, '11–6, 11–7, 11–8, 11–4', '2025-11-29 23:54:47', '2025-11-29 23:54:47');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0037', 'ATH0001', 'West Java Women’s Table Tennis Open', 'city_regional_club', 'PTMSI Jawa Barat', 'Bandung, Indonesia', '2025-02-05', '2025-02-05', 'Peringkat 4 West Java Women’s Table Tennis Open', 'Perorangan Putri', 'Kalah perebutan peringkat 3 dengan skor 2–3. \nTotal points match: 48–51.', NULL, 'non_podium', 4, '2–3 (Bronze Match)', '2025-11-29 23:56:15', '2025-11-29 23:56:15');
INSERT INTO `achievements` (`achievement_id`, `athlete_id`, `event_name`, `competition_level`, `organizer`, `location`, `start_date`, `end_date`, `achievement_name`, `event_number`, `notes`, `evidence_file`, `medal_rank`, `rank`, `result`, `created_at`, `updated_at`) VALUES('ACH0038', 'ATH0001', 'Cimahi Women’s Table Tennis Club Cup', 'city_regional_club', 'Cimahi Table Tennis Community', 'Cimahi, Indonesia', '2024-01-10', '2024-01-10', 'Juara 3 Cimahi Women’s TT Club Cup', 'Perorangan Putri', 'Rata-rata smash speed: 62 km/jam. \nMenang perebutan posisi 3: 3–1.', NULL, 'bronze', 3, '11–9, 11–8, 9–11, 11–7', '2025-11-29 23:57:24', '2025-11-29 23:57:24');
SQL);
    }
}
