<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class AthletesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('athletes')->delete();
        
        \DB::table('athletes')->insert(array (
            0 => 
            array (
                'athlete_id' => 'ATH0001',
                'name' => 'Maryam Fatimah Ahyuddin',
                'avatar' => 'athletes/avatars/01KC92EPKJJKJBF9640H5YEV6E.jpg',
                'gender' => 'female',
                'birthdate' => '2004-08-21',
                'contact' => '+62 812-1353-5975',
                'sport_category' => 'olympic',
                'sport' => 'Tenis Meja',
                'height' => 161.0,
                'weight' => 46.0,
                'status' => 'fit',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2026-06-09',
                'created_at' => '2025-11-29 11:26:30',
                'updated_at' => '2025-12-12 10:42:07',
            ),
            1 => 
            array (
                'athlete_id' => 'ATH0002',
                'name' => 'Neva Talitha Amodia',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2005-09-17',
                'contact' => '+62 821-7243-3157',
                'sport_category' => 'olympic',
                'sport' => 'Berkuda',
                'height' => 163.0,
                'weight' => 45.0,
                'status' => 'restricted',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2025-12-30',
                'created_at' => '2025-11-29 13:45:47',
                'updated_at' => '2025-12-09 04:46:55',
            ),
            2 => 
            array (
                'athlete_id' => 'ATH0003',
                'name' => 'Vanesha Aulia Anggraeni',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2005-05-13',
                'contact' => '+62 813-2112-7021',
                'sport_category' => 'non_olympic',
                'sport' => 'Pencak Silat',
                'height' => 163.0,
                'weight' => 49.0,
                'status' => 'active_therapy',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2025-12-30',
                'created_at' => '2025-11-29 20:44:01',
                'updated_at' => '2025-12-09 04:24:59',
            ),
            3 => 
            array (
                'athlete_id' => 'ATH0004',
                'name' => 'Chepi Luna Sereniti',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2005-11-11',
                'contact' => '+62 895-0622-8904',
                'sport_category' => 'non_olympic',
                'sport' => 'Muay Thai',
                'height' => 170.0,
                'weight' => 50.0,
                'status' => 'fit',
                'last_screening_date' => '2025-12-13',
                'next_screening_due' => '2026-06-13',
                'created_at' => '2025-11-29 20:48:39',
                'updated_at' => '2025-12-13 08:40:30',
            ),
            4 => 
            array (
                'athlete_id' => 'ATH0005',
                'name' => 'Tyara Yulian Putri',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2005-07-14',
                'contact' => '+62 896-2885-8002',
                'sport_category' => 'olympic',
                'sport' => 'Anggar',
                'height' => 165.0,
                'weight' => 47.0,
                'status' => 'restricted',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2025-12-30',
                'created_at' => '2025-11-29 20:51:24',
                'updated_at' => '2025-12-09 04:45:55',
            ),
            5 => 
            array (
                'athlete_id' => 'ATH0006',
                'name' => 'Syakira Naura Amalia',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2005-05-08',
                'contact' => '+62 895-0569-4436',
                'sport_category' => 'olympic',
                'sport' => 'Bola Basket',
                'height' => 160.0,
                'weight' => 48.0,
                'status' => 'under_monitoring',
                'last_screening_date' => '2025-12-13',
                'next_screening_due' => '2026-06-13',
                'created_at' => '2025-11-29 20:53:21',
                'updated_at' => '2025-12-13 08:39:28',
            ),
            6 => 
            array (
                'athlete_id' => 'ATH0007',
                'name' => 'Brando Franco Windah',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1992-03-14',
                'contact' => '+62 898-8066-222',
                'sport_category' => 'non_olympic',
                'sport' => 'Esport',
                'height' => 185.0,
                'weight' => 82.0,
                'status' => 'active_therapy',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2025-12-30',
                'created_at' => '2025-11-29 20:59:13',
                'updated_at' => '2025-12-09 04:36:18',
            ),
            7 => 
            array (
                'athlete_id' => 'ATH0008',
                'name' => 'Farrel Dharmawan',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-07-03',
                'contact' => '+62 877-8752-2590',
                'sport_category' => 'olympic',
                'sport' => 'Bola Basket',
                'height' => 183.0,
                'weight' => 72.0,
                'status' => 'active_therapy',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2025-12-30',
                'created_at' => '2025-11-29 21:05:09',
                'updated_at' => '2025-12-09 04:38:19',
            ),
            8 => 
            array (
                'athlete_id' => 'ATH0009',
                'name' => 'Suara Jingga',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2005-12-08',
                'contact' => '+62 821-2789-4461',
                'sport_category' => 'olympic',
                'sport' => 'Panahan',
                'height' => 163.0,
                'weight' => 49.0,
                'status' => 'under_monitoring',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2026-06-09',
                'created_at' => '2025-11-29 21:32:18',
                'updated_at' => '2025-12-09 04:46:23',
            ),
            9 => 
            array (
                'athlete_id' => 'ATH0010',
                'name' => 'Jaudan Afzal',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-10-09',
                'contact' => '+62 812-9522-0076',
                'sport_category' => 'olympic',
                'sport' => 'Sepak Bola',
                'height' => 175.0,
                'weight' => 52.0,
                'status' => 'active_therapy',
                'last_screening_date' => '2025-12-09',
                'next_screening_due' => '2025-12-30',
                'created_at' => '2025-11-29 21:38:15',
                'updated_at' => '2025-12-09 04:44:05',
            ),
            10 => 
            array (
                'athlete_id' => 'ATH0011',
                'name' => 'Atlet Angkat Besi 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-12-12',
                'contact' => '08000000011',
                'sport_category' => 'olympic',
                'sport' => 'Angkat Besi',
                'height' => 171.0,
                'weight' => 61.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            11 => 
            array (
                'athlete_id' => 'ATH0012',
                'name' => 'Atlet Atletik 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-01-13',
                'contact' => '08000000012',
                'sport_category' => 'olympic',
                'sport' => 'Atletik',
                'height' => 172.0,
                'weight' => 62.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            12 => 
            array (
                'athlete_id' => 'ATH0013',
                'name' => 'Atlet Balap Sepeda 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-02-14',
                'contact' => '08000000013',
                'sport_category' => 'olympic',
                'sport' => 'Balap Sepeda',
                'height' => 173.0,
                'weight' => 63.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            13 => 
            array (
                'athlete_id' => 'ATH0014',
                'name' => 'Atlet Bisbol - Sofbol 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-03-15',
                'contact' => '08000000014',
                'sport_category' => 'olympic',
                'sport' => 'Bisbol - Sofbol',
                'height' => 174.0,
                'weight' => 64.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            14 => 
            array (
                'athlete_id' => 'ATH0015',
                'name' => 'Atlet Bisbol - Sofbol 2',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-04-16',
                'contact' => '08000000015',
                'sport_category' => 'olympic',
                'sport' => 'Bisbol - Sofbol',
                'height' => 175.0,
                'weight' => 65.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            15 => 
            array (
                'athlete_id' => 'ATH0016',
                'name' => 'Atlet Bisbol - Sofbol 3',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-05-17',
                'contact' => '08000000016',
                'sport_category' => 'olympic',
                'sport' => 'Bisbol - Sofbol',
                'height' => 176.0,
                'weight' => 66.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            16 => 
            array (
                'athlete_id' => 'ATH0017',
                'name' => 'Atlet Bisbol - Sofbol 4',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-06-18',
                'contact' => '08000000017',
                'sport_category' => 'olympic',
                'sport' => 'Bisbol - Sofbol',
                'height' => 177.0,
                'weight' => 67.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            17 => 
            array (
                'athlete_id' => 'ATH0018',
                'name' => 'Atlet Bola Tangan 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-07-19',
                'contact' => '08000000018',
                'sport_category' => 'olympic',
                'sport' => 'Bola Tangan',
                'height' => 178.0,
                'weight' => 68.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            18 => 
            array (
                'athlete_id' => 'ATH0019',
                'name' => 'Atlet Bola Voli 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-08-20',
                'contact' => '08000000019',
                'sport_category' => 'olympic',
                'sport' => 'Bola Voli',
                'height' => 179.0,
                'weight' => 69.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            19 => 
            array (
                'athlete_id' => 'ATH0020',
                'name' => 'Atlet Bola Voli 2',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-09-21',
                'contact' => '08000000020',
                'sport_category' => 'olympic',
                'sport' => 'Bola Voli',
                'height' => 180.0,
                'weight' => 50.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            20 => 
            array (
                'athlete_id' => 'ATH0021',
                'name' => 'Atlet Bola Voli 3',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-10-22',
                'contact' => '08000000021',
                'sport_category' => 'olympic',
                'sport' => 'Bola Voli',
                'height' => 181.0,
                'weight' => 51.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            21 => 
            array (
                'athlete_id' => 'ATH0022',
                'name' => 'Atlet Bola Voli 4',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-11-23',
                'contact' => '08000000022',
                'sport_category' => 'olympic',
                'sport' => 'Bola Voli',
                'height' => 182.0,
                'weight' => 52.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            22 => 
            array (
                'athlete_id' => 'ATH0023',
                'name' => 'Atlet Bulutangkis 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-12-24',
                'contact' => '08000000023',
                'sport_category' => 'olympic',
                'sport' => 'Bulutangkis',
                'height' => 183.0,
                'weight' => 53.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            23 => 
            array (
                'athlete_id' => 'ATH0024',
                'name' => 'Atlet Dayung 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-01-25',
                'contact' => '08000000024',
                'sport_category' => 'olympic',
                'sport' => 'Dayung',
                'height' => 184.0,
                'weight' => 54.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            24 => 
            array (
                'athlete_id' => 'ATH0025',
                'name' => 'Atlet Golf 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-02-26',
                'contact' => '08000000025',
                'sport_category' => 'olympic',
                'sport' => 'Golf',
                'height' => 160.0,
                'weight' => 55.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            25 => 
            array (
                'athlete_id' => 'ATH0026',
                'name' => 'Atlet Gulat 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-03-27',
                'contact' => '08000000026',
                'sport_category' => 'olympic',
                'sport' => 'Gulat',
                'height' => 161.0,
                'weight' => 56.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            26 => 
            array (
                'athlete_id' => 'ATH0027',
                'name' => 'Atlet Hoki 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-04-28',
                'contact' => '08000000027',
                'sport_category' => 'olympic',
                'sport' => 'Hoki',
                'height' => 162.0,
                'weight' => 57.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            27 => 
            array (
                'athlete_id' => 'ATH0028',
                'name' => 'Atlet Hoki 2',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-05-01',
                'contact' => '08000000028',
                'sport_category' => 'olympic',
                'sport' => 'Hoki',
                'height' => 163.0,
                'weight' => 58.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            28 => 
            array (
                'athlete_id' => 'ATH0029',
                'name' => 'Atlet Hoki 3',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-06-02',
                'contact' => '08000000029',
                'sport_category' => 'olympic',
                'sport' => 'Hoki',
                'height' => 164.0,
                'weight' => 59.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            29 => 
            array (
                'athlete_id' => 'ATH0030',
                'name' => 'Atlet Hoki 4',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-07-03',
                'contact' => '08000000030',
                'sport_category' => 'olympic',
                'sport' => 'Hoki',
                'height' => 165.0,
                'weight' => 60.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            30 => 
            array (
                'athlete_id' => 'ATH0031',
                'name' => 'Atlet Hoki Es 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-08-04',
                'contact' => '08000000031',
                'sport_category' => 'olympic',
                'sport' => 'Hoki Es',
                'height' => 166.0,
                'weight' => 61.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            31 => 
            array (
                'athlete_id' => 'ATH0032',
                'name' => 'Atlet Hoki Es 2',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-09-05',
                'contact' => '08000000032',
                'sport_category' => 'olympic',
                'sport' => 'Hoki Es',
                'height' => 167.0,
                'weight' => 62.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            32 => 
            array (
                'athlete_id' => 'ATH0033',
                'name' => 'Atlet Hoki Es 3',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-10-06',
                'contact' => '08000000033',
                'sport_category' => 'olympic',
                'sport' => 'Hoki Es',
                'height' => 168.0,
                'weight' => 63.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            33 => 
            array (
                'athlete_id' => 'ATH0034',
                'name' => 'Atlet Hoki Es 4',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-11-07',
                'contact' => '08000000034',
                'sport_category' => 'olympic',
                'sport' => 'Hoki Es',
                'height' => 169.0,
                'weight' => 64.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            34 => 
            array (
                'athlete_id' => 'ATH0035',
                'name' => 'Atlet Judo 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-12-08',
                'contact' => '08000000035',
                'sport_category' => 'olympic',
                'sport' => 'Judo',
                'height' => 170.0,
                'weight' => 65.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            35 => 
            array (
                'athlete_id' => 'ATH0036',
                'name' => 'Atlet Kano 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-01-09',
                'contact' => '08000000036',
                'sport_category' => 'olympic',
                'sport' => 'Kano',
                'height' => 171.0,
                'weight' => 66.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            36 => 
            array (
                'athlete_id' => 'ATH0037',
                'name' => 'Atlet Karate 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-02-10',
                'contact' => '08000000037',
                'sport_category' => 'olympic',
                'sport' => 'Karate',
                'height' => 172.0,
                'weight' => 67.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            37 => 
            array (
                'athlete_id' => 'ATH0038',
                'name' => 'Atlet Layar 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-03-11',
                'contact' => '08000000038',
                'sport_category' => 'olympic',
                'sport' => 'Layar',
                'height' => 173.0,
                'weight' => 68.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            38 => 
            array (
                'athlete_id' => 'ATH0039',
                'name' => 'Atlet Loncat Indah 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-04-12',
                'contact' => '08000000039',
                'sport_category' => 'olympic',
                'sport' => 'Loncat Indah',
                'height' => 174.0,
                'weight' => 69.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            39 => 
            array (
                'athlete_id' => 'ATH0040',
                'name' => 'Atlet Menembak 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-05-13',
                'contact' => '08000000040',
                'sport_category' => 'olympic',
                'sport' => 'Menembak',
                'height' => 175.0,
                'weight' => 50.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            40 => 
            array (
                'athlete_id' => 'ATH0041',
                'name' => 'Atlet Pancalomba Modern 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-06-14',
                'contact' => '08000000041',
                'sport_category' => 'olympic',
                'sport' => 'Pancalomba Modern',
                'height' => 176.0,
                'weight' => 51.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            41 => 
            array (
                'athlete_id' => 'ATH0042',
                'name' => 'Atlet Panjat Tebing 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-07-15',
                'contact' => '08000000042',
                'sport_category' => 'olympic',
                'sport' => 'Panjat Tebing',
                'height' => 177.0,
                'weight' => 52.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            42 => 
            array (
                'athlete_id' => 'ATH0043',
                'name' => 'Atlet Polo Air 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-08-16',
                'contact' => '08000000043',
                'sport_category' => 'olympic',
                'sport' => 'Polo Air',
                'height' => 178.0,
                'weight' => 53.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            43 => 
            array (
                'athlete_id' => 'ATH0044',
                'name' => 'Atlet Polo Air 2',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-09-17',
                'contact' => '08000000044',
                'sport_category' => 'olympic',
                'sport' => 'Polo Air',
                'height' => 179.0,
                'weight' => 54.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            44 => 
            array (
                'athlete_id' => 'ATH0045',
                'name' => 'Atlet Polo Air 3',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-10-18',
                'contact' => '08000000045',
                'sport_category' => 'olympic',
                'sport' => 'Polo Air',
                'height' => 180.0,
                'weight' => 55.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            45 => 
            array (
                'athlete_id' => 'ATH0046',
                'name' => 'Atlet Polo Air 4',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-11-19',
                'contact' => '08000000046',
                'sport_category' => 'olympic',
                'sport' => 'Polo Air',
                'height' => 181.0,
                'weight' => 56.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            46 => 
            array (
                'athlete_id' => 'ATH0047',
                'name' => 'Atlet Renang 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-12-20',
                'contact' => '08000000047',
                'sport_category' => 'olympic',
                'sport' => 'Renang',
                'height' => 182.0,
                'weight' => 57.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            47 => 
            array (
                'athlete_id' => 'ATH0048',
                'name' => 'Atlet Renang Indah 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-01-21',
                'contact' => '08000000048',
                'sport_category' => 'olympic',
                'sport' => 'Renang Indah',
                'height' => 183.0,
                'weight' => 58.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            48 => 
            array (
                'athlete_id' => 'ATH0049',
                'name' => 'Atlet Renang Maraton 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-02-22',
                'contact' => '08000000049',
                'sport_category' => 'olympic',
                'sport' => 'Renang Maraton',
                'height' => 184.0,
                'weight' => 59.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            49 => 
            array (
                'athlete_id' => 'ATH0050',
                'name' => 'Atlet Rugby 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-03-23',
                'contact' => '08000000050',
                'sport_category' => 'olympic',
                'sport' => 'Rugby',
                'height' => 160.0,
                'weight' => 60.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            50 => 
            array (
                'athlete_id' => 'ATH0051',
                'name' => 'Atlet Rugby 2',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-04-24',
                'contact' => '08000000051',
                'sport_category' => 'olympic',
                'sport' => 'Rugby',
                'height' => 161.0,
                'weight' => 61.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            51 => 
            array (
                'athlete_id' => 'ATH0052',
                'name' => 'Atlet Rugby 3',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-05-25',
                'contact' => '08000000052',
                'sport_category' => 'olympic',
                'sport' => 'Rugby',
                'height' => 162.0,
                'weight' => 62.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            52 => 
            array (
                'athlete_id' => 'ATH0053',
                'name' => 'Atlet Rugby 4',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-06-26',
                'contact' => '08000000053',
                'sport_category' => 'olympic',
                'sport' => 'Rugby',
                'height' => 163.0,
                'weight' => 63.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            53 => 
            array (
                'athlete_id' => 'ATH0054',
                'name' => 'Atlet Selancar Ombak 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-07-27',
                'contact' => '08000000054',
                'sport_category' => 'olympic',
                'sport' => 'Selancar Ombak',
                'height' => 164.0,
                'weight' => 64.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            54 => 
            array (
                'athlete_id' => 'ATH0055',
                'name' => 'Atlet Senam 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-08-28',
                'contact' => '08000000055',
                'sport_category' => 'olympic',
                'sport' => 'Senam',
                'height' => 165.0,
                'weight' => 65.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            55 => 
            array (
                'athlete_id' => 'ATH0056',
                'name' => 'Atlet Skateboard 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-09-01',
                'contact' => '08000000056',
                'sport_category' => 'olympic',
                'sport' => 'Skateboard',
                'height' => 166.0,
                'weight' => 66.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            56 => 
            array (
                'athlete_id' => 'ATH0057',
                'name' => 'Atlet Taekwondo 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-10-02',
                'contact' => '08000000057',
                'sport_category' => 'olympic',
                'sport' => 'Taekwondo',
                'height' => 167.0,
                'weight' => 67.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            57 => 
            array (
                'athlete_id' => 'ATH0058',
                'name' => 'Atlet Tenis 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-11-03',
                'contact' => '08000000058',
                'sport_category' => 'olympic',
                'sport' => 'Tenis',
                'height' => 168.0,
                'weight' => 68.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            58 => 
            array (
                'athlete_id' => 'ATH0059',
                'name' => 'Atlet Tinju 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-12-04',
                'contact' => '08000000059',
                'sport_category' => 'olympic',
                'sport' => 'Tinju',
                'height' => 169.0,
                'weight' => 69.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            59 => 
            array (
                'athlete_id' => 'ATH0060',
                'name' => 'Atlet Triathlon 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-01-05',
                'contact' => '08000000060',
                'sport_category' => 'olympic',
                'sport' => 'Triathlon',
                'height' => 170.0,
                'weight' => 50.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            60 => 
            array (
                'athlete_id' => 'ATH0061',
                'name' => 'Atlet Aero Sport 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-02-06',
                'contact' => '08000000061',
                'sport_category' => 'non_olympic',
                'sport' => 'Aero Sport',
                'height' => 171.0,
                'weight' => 51.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            61 => 
            array (
                'athlete_id' => 'ATH0062',
                'name' => 'Atlet Billiard 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-03-07',
                'contact' => '08000000062',
                'sport_category' => 'non_olympic',
                'sport' => 'Billiard',
                'height' => 172.0,
                'weight' => 52.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            62 => 
            array (
                'athlete_id' => 'ATH0063',
                'name' => 'Atlet Bowling 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-04-08',
                'contact' => '08000000063',
                'sport_category' => 'non_olympic',
                'sport' => 'Bowling',
                'height' => 173.0,
                'weight' => 53.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            63 => 
            array (
                'athlete_id' => 'ATH0064',
                'name' => 'Atlet Breakdancing 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-05-09',
                'contact' => '08000000064',
                'sport_category' => 'non_olympic',
                'sport' => 'Breakdancing',
                'height' => 174.0,
                'weight' => 54.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            64 => 
            array (
                'athlete_id' => 'ATH0065',
                'name' => 'Atlet Bridge 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-06-10',
                'contact' => '08000000065',
                'sport_category' => 'non_olympic',
                'sport' => 'Bridge',
                'height' => 175.0,
                'weight' => 55.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            65 => 
            array (
                'athlete_id' => 'ATH0066',
                'name' => 'Atlet Catur 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-07-11',
                'contact' => '08000000066',
                'sport_category' => 'non_olympic',
                'sport' => 'Catur',
                'height' => 176.0,
                'weight' => 56.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            66 => 
            array (
                'athlete_id' => 'ATH0067',
                'name' => 'Atlet Cricket 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-08-12',
                'contact' => '08000000067',
                'sport_category' => 'non_olympic',
                'sport' => 'Cricket',
                'height' => 177.0,
                'weight' => 57.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            67 => 
            array (
                'athlete_id' => 'ATH0068',
                'name' => 'Atlet Cricket 2',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-09-13',
                'contact' => '08000000068',
                'sport_category' => 'non_olympic',
                'sport' => 'Cricket',
                'height' => 178.0,
                'weight' => 58.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            68 => 
            array (
                'athlete_id' => 'ATH0069',
                'name' => 'Atlet Cricket 3',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-10-14',
                'contact' => '08000000069',
                'sport_category' => 'non_olympic',
                'sport' => 'Cricket',
                'height' => 179.0,
                'weight' => 59.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            69 => 
            array (
                'athlete_id' => 'ATH0070',
                'name' => 'Atlet Cricket 4',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-11-15',
                'contact' => '08000000070',
                'sport_category' => 'non_olympic',
                'sport' => 'Cricket',
                'height' => 180.0,
                'weight' => 60.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            70 => 
            array (
                'athlete_id' => 'ATH0071',
                'name' => 'Atlet Dansa 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-12-16',
                'contact' => '08000000071',
                'sport_category' => 'non_olympic',
                'sport' => 'Dansa',
                'height' => 181.0,
                'weight' => 61.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            71 => 
            array (
                'athlete_id' => 'ATH0072',
                'name' => 'Atlet Dragon Boat 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-01-17',
                'contact' => '08000000072',
                'sport_category' => 'non_olympic',
                'sport' => 'Dragon Boat',
                'height' => 182.0,
                'weight' => 62.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            72 => 
            array (
                'athlete_id' => 'ATH0073',
                'name' => 'Atlet Dragon Boat 2',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-02-18',
                'contact' => '08000000073',
                'sport_category' => 'non_olympic',
                'sport' => 'Dragon Boat',
                'height' => 183.0,
                'weight' => 63.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            73 => 
            array (
                'athlete_id' => 'ATH0074',
                'name' => 'Atlet Dragon Boat 3',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-03-19',
                'contact' => '08000000074',
                'sport_category' => 'non_olympic',
                'sport' => 'Dragon Boat',
                'height' => 184.0,
                'weight' => 64.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            74 => 
            array (
                'athlete_id' => 'ATH0075',
                'name' => 'Atlet Dragon Boat 4',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-04-20',
                'contact' => '08000000075',
                'sport_category' => 'non_olympic',
                'sport' => 'Dragon Boat',
                'height' => 160.0,
                'weight' => 65.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            75 => 
            array (
                'athlete_id' => 'ATH0076',
                'name' => 'Atlet Floorball 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-05-21',
                'contact' => '08000000076',
                'sport_category' => 'non_olympic',
                'sport' => 'Floorball',
                'height' => 161.0,
                'weight' => 66.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            76 => 
            array (
                'athlete_id' => 'ATH0077',
                'name' => 'Atlet Floorball 2',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-06-22',
                'contact' => '08000000077',
                'sport_category' => 'non_olympic',
                'sport' => 'Floorball',
                'height' => 162.0,
                'weight' => 67.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            77 => 
            array (
                'athlete_id' => 'ATH0078',
                'name' => 'Atlet Floorball 3',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-07-23',
                'contact' => '08000000078',
                'sport_category' => 'non_olympic',
                'sport' => 'Floorball',
                'height' => 163.0,
                'weight' => 68.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            78 => 
            array (
                'athlete_id' => 'ATH0079',
                'name' => 'Atlet Floorball 4',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-08-24',
                'contact' => '08000000079',
                'sport_category' => 'non_olympic',
                'sport' => 'Floorball',
                'height' => 164.0,
                'weight' => 69.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            79 => 
            array (
                'athlete_id' => 'ATH0080',
                'name' => 'Atlet Gateball 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-09-25',
                'contact' => '08000000080',
                'sport_category' => 'non_olympic',
                'sport' => 'Gateball',
                'height' => 165.0,
                'weight' => 50.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            80 => 
            array (
                'athlete_id' => 'ATH0081',
                'name' => 'Atlet Jetski 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-10-26',
                'contact' => '08000000081',
                'sport_category' => 'non_olympic',
                'sport' => 'Jetski',
                'height' => 166.0,
                'weight' => 51.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            81 => 
            array (
                'athlete_id' => 'ATH0082',
                'name' => 'Atlet Jujitsu 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-11-27',
                'contact' => '08000000082',
                'sport_category' => 'non_olympic',
                'sport' => 'Jujitsu',
                'height' => 167.0,
                'weight' => 52.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            82 => 
            array (
                'athlete_id' => 'ATH0083',
                'name' => 'Atlet Kabaddi 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-12-28',
                'contact' => '08000000083',
                'sport_category' => 'non_olympic',
                'sport' => 'Kabaddi',
                'height' => 168.0,
                'weight' => 53.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            83 => 
            array (
                'athlete_id' => 'ATH0084',
                'name' => 'Atlet Kempo 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-01-01',
                'contact' => '08000000084',
                'sport_category' => 'non_olympic',
                'sport' => 'Kempo',
                'height' => 169.0,
                'weight' => 54.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            84 => 
            array (
                'athlete_id' => 'ATH0085',
                'name' => 'Atlet Kick Boxing 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-02-02',
                'contact' => '08000000085',
                'sport_category' => 'non_olympic',
                'sport' => 'Kick Boxing',
                'height' => 170.0,
                'weight' => 55.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            85 => 
            array (
                'athlete_id' => 'ATH0086',
                'name' => 'Atlet Korfball 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-03-03',
                'contact' => '08000000086',
                'sport_category' => 'non_olympic',
                'sport' => 'Korfball',
                'height' => 171.0,
                'weight' => 56.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            86 => 
            array (
                'athlete_id' => 'ATH0087',
                'name' => 'Atlet Korfball 2',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-04-04',
                'contact' => '08000000087',
                'sport_category' => 'non_olympic',
                'sport' => 'Korfball',
                'height' => 172.0,
                'weight' => 57.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            87 => 
            array (
                'athlete_id' => 'ATH0088',
                'name' => 'Atlet Korfball 3',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-05-05',
                'contact' => '08000000088',
                'sport_category' => 'non_olympic',
                'sport' => 'Korfball',
                'height' => 173.0,
                'weight' => 58.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            88 => 
            array (
                'athlete_id' => 'ATH0089',
                'name' => 'Atlet Korfball 4',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-06-06',
                'contact' => '08000000089',
                'sport_category' => 'non_olympic',
                'sport' => 'Korfball',
                'height' => 174.0,
                'weight' => 59.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            89 => 
            array (
                'athlete_id' => 'ATH0090',
                'name' => 'Atlet Kurash 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-07-07',
                'contact' => '08000000090',
                'sport_category' => 'non_olympic',
                'sport' => 'Kurash',
                'height' => 175.0,
                'weight' => 60.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            90 => 
            array (
                'athlete_id' => 'ATH0091',
                'name' => 'Atlet Motor 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-08-08',
                'contact' => '08000000091',
                'sport_category' => 'non_olympic',
                'sport' => 'Motor',
                'height' => 176.0,
                'weight' => 61.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            91 => 
            array (
                'athlete_id' => 'ATH0092',
                'name' => 'Atlet Petanque 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-09-09',
                'contact' => '08000000092',
                'sport_category' => 'non_olympic',
                'sport' => 'Petanque',
                'height' => 177.0,
                'weight' => 62.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            92 => 
            array (
                'athlete_id' => 'ATH0093',
                'name' => 'Atlet Rugby Sevens 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-10-10',
                'contact' => '08000000093',
                'sport_category' => 'non_olympic',
                'sport' => 'Rugby Sevens',
                'height' => 178.0,
                'weight' => 63.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            93 => 
            array (
                'athlete_id' => 'ATH0094',
                'name' => 'Atlet Rugby Sevens 2',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-11-11',
                'contact' => '08000000094',
                'sport_category' => 'non_olympic',
                'sport' => 'Rugby Sevens',
                'height' => 179.0,
                'weight' => 64.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            94 => 
            array (
                'athlete_id' => 'ATH0095',
                'name' => 'Atlet Rugby Sevens 3',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-12-12',
                'contact' => '08000000095',
                'sport_category' => 'non_olympic',
                'sport' => 'Rugby Sevens',
                'height' => 180.0,
                'weight' => 65.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            95 => 
            array (
                'athlete_id' => 'ATH0096',
                'name' => 'Atlet Rugby Sevens 4',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-01-13',
                'contact' => '08000000096',
                'sport_category' => 'non_olympic',
                'sport' => 'Rugby Sevens',
                'height' => 181.0,
                'weight' => 66.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            96 => 
            array (
                'athlete_id' => 'ATH0097',
                'name' => 'Atlet Sambo 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2002-02-14',
                'contact' => '08000000097',
                'sport_category' => 'non_olympic',
                'sport' => 'Sambo',
                'height' => 182.0,
                'weight' => 67.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            97 => 
            array (
                'athlete_id' => 'ATH0098',
                'name' => 'Atlet Sepak Takraw 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2003-03-15',
                'contact' => '08000000098',
                'sport_category' => 'non_olympic',
                'sport' => 'Sepak Takraw',
                'height' => 183.0,
                'weight' => 68.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            98 => 
            array (
                'athlete_id' => 'ATH0099',
                'name' => 'Atlet Sepak Takraw 2',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2004-04-16',
                'contact' => '08000000099',
                'sport_category' => 'non_olympic',
                'sport' => 'Sepak Takraw',
                'height' => 184.0,
                'weight' => 69.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            99 => 
            array (
                'athlete_id' => 'ATH0100',
                'name' => 'Atlet Sepak Takraw 3',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1995-05-17',
                'contact' => '08000000100',
                'sport_category' => 'non_olympic',
                'sport' => 'Sepak Takraw',
                'height' => 160.0,
                'weight' => 50.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            100 => 
            array (
                'athlete_id' => 'ATH0101',
                'name' => 'Atlet Sepak Takraw 4',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1996-06-18',
                'contact' => '08000000101',
                'sport_category' => 'non_olympic',
                'sport' => 'Sepak Takraw',
                'height' => 161.0,
                'weight' => 51.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            101 => 
            array (
                'athlete_id' => 'ATH0102',
                'name' => 'Atlet Sepatu Roda 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1997-07-19',
                'contact' => '08000000102',
                'sport_category' => 'non_olympic',
                'sport' => 'Sepatu Roda',
                'height' => 162.0,
                'weight' => 52.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            102 => 
            array (
                'athlete_id' => 'ATH0103',
                'name' => 'Atlet Soft Tennis 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '1998-08-20',
                'contact' => '08000000103',
                'sport_category' => 'non_olympic',
                'sport' => 'Soft Tennis',
                'height' => 163.0,
                'weight' => 53.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            103 => 
            array (
                'athlete_id' => 'ATH0104',
                'name' => 'Atlet Squash 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '1999-09-21',
                'contact' => '08000000104',
                'sport_category' => 'non_olympic',
                'sport' => 'Squash',
                'height' => 164.0,
                'weight' => 54.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            104 => 
            array (
                'athlete_id' => 'ATH0105',
                'name' => 'Atlet Wakeboarding 1',
                'avatar' => NULL,
                'gender' => 'male',
                'birthdate' => '2000-10-22',
                'contact' => '08000000105',
                'sport_category' => 'non_olympic',
                'sport' => 'Wakeboarding',
                'height' => 165.0,
                'weight' => 55.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            105 => 
            array (
                'athlete_id' => 'ATH0106',
                'name' => 'Atlet Woodball 1',
                'avatar' => NULL,
                'gender' => 'female',
                'birthdate' => '2001-11-23',
                'contact' => '08000000106',
                'sport_category' => 'non_olympic',
                'sport' => 'Woodball',
                'height' => 166.0,
                'weight' => 56.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            106 => 
            array (
                'athlete_id' => 'ATH0107',
                'name' => 'Atlet Wushu 1',
                'avatar' => 'athletes/avatars/01KC92C6TE0BB2RVP9BYZDV3GD.jpg',
                'gender' => 'male',
                'birthdate' => '2002-12-24',
                'contact' => '08000000107',
                'sport_category' => 'non_olympic',
                'sport' => 'Wushu',
                'height' => 167.0,
                'weight' => 57.0,
                'status' => 'not_screened',
                'last_screening_date' => NULL,
                'next_screening_due' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-12 10:40:45',
            ),
        ));
        
        
    }
}