<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class HealthScreeningsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('health_screenings')->delete();
        
        \DB::table('health_screenings')->insert(array (
            0 => 
            array (
                'screening_id' => 'SCR0001',
                'auto_increment' => 1,
                'athlete_id' => 'ATH0002',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:19:39',
                'blood_pressure' => '100/64',
                'heart_rate' => 82,
                'temperature' => '36.8',
                'respiration_rate' => 18,
                'oxygen_saturation' => 99,
                'chief_complaint' => 'Nyeri punggung bawah sejak 4–5 hari terakhir, terutama setelah latihan jumping.',
                'injury_history' => 'Pernah mengalami tightness dan spasme ringan pada lumbar 3 bulan lalu setelah sesi latihan intens. Sudah pulih namun keluhan muncul lagi minggu ini.',
            'pain_location' => 'Lower back (lumbar), terutama L3–L5.',
                'pain_scale' => 4,
            'training_load' => 'Sedang–berat (latihan jumping + dressage)',
            'training_frequency' => '5x per minggu (1.5–2 jam per sesi)',
                'notes' => 'Hindari latihan jumping sampai minggu pertama terapi selesai.
Fokus ke latihan dressage teknik ringan dan kontrol postur.
Eval lumbar mobility di minggu ke-2 terapi untuk mencegah recurrent strain.',
                'report_file_path' => 'health-reports/01KC0NC2T2S4E0AYSK3SWEYH2V.pdf',
                'created_at' => '2025-12-09 04:19:34',
                'updated_at' => '2025-12-09 04:19:39',
            ),
            1 => 
            array (
                'screening_id' => 'SCR0002',
                'auto_increment' => 2,
                'athlete_id' => 'ATH0001',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:22:12',
                'blood_pressure' => '105/70',
                'heart_rate' => 76,
                'temperature' => '36.6',
                'respiration_rate' => 17,
                'oxygen_saturation' => 98,
                'chief_complaint' => 'Nyeri bahu kanan saat melakukan forehand topspin & smash cepat selama 5–6 hari terakhir.',
                'injury_history' => 'Tendinitis ringan 6 bulan lalu ketika intensitas latihan meningkat menjelang turnamen.',
                'pain_location' => 'Bahu kanan, terutama area deltoid anterior.',
                'pain_scale' => 5,
            'training_load' => 'Sedang–berat (kombinasi teknik + fisik)',
                'training_frequency' => '5x per minggu, ±2 jam per sesi',
                'notes' => 'Kurangi latihan yang melibatkan power smash selama 1–2 minggu. Fokus pada footwork & kontrol bola.
Evaluasi bahu selama terapi minggu ke-2 untuk mencegah impingement.',
                'report_file_path' => 'health-reports/01KC0NGTPB821Z5CC9625HXVMR.pdf',
                'created_at' => '2025-12-09 04:22:10',
                'updated_at' => '2025-12-09 04:22:12',
            ),
            2 => 
            array (
                'screening_id' => 'SCR0003',
                'auto_increment' => 3,
                'athlete_id' => 'ATH0003',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:25:02',
                'blood_pressure' => '108/72',
                'heart_rate' => 78,
                'temperature' => '36.7',
                'respiration_rate' => 18,
                'oxygen_saturation' => 98,
            'chief_complaint' => 'Nyeri pada pergelangan kaki kiri sejak latihan tendangan T usus (T kick) 3 hari lalu. Nyeri makin muncul ketika pivot atau mendarat setelah tendangan.',
                'injury_history' => 'Pernah mengalami ankle sprain ringan 1 tahun lalu, tapi sudah pulih total.',
            'pain_location' => 'Pergelangan kaki kiri (lateral ankle)',
                'pain_scale' => 4,
            'training_load' => 'Sedang–berat (latihan teknik + sparring)',
                'training_frequency' => '5x/minggu, 2 jam per sesi',
                'notes' => 'Hindari sparring dan tendangan yang memerlukan pivot kuat.
Disarankan latihan shadowing & teknik non-impact selama minggu pertama terapi.
Evaluasi range of motion ankle minggu ke-2.',
                'report_file_path' => 'health-reports/01KC0NNZPBSENZAVJCDZRXRW8J.pdf',
                'created_at' => '2025-12-09 04:24:59',
                'updated_at' => '2025-12-09 04:25:02',
            ),
            3 => 
            array (
                'screening_id' => 'SCR0004',
                'auto_increment' => 4,
                'athlete_id' => 'ATH0004',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:30:12',
                'blood_pressure' => '108/70',
                'heart_rate' => 81,
                'temperature' => '36.7',
                'respiration_rate' => 18,
                'oxygen_saturation' => 98,
            'chief_complaint' => 'Nyeri pada lutut kanan setelah latihan checking low kick dan repetisi teep (front kick). Nyeri terasa saat menekuk lutut dan saat menahan beban.',
                'injury_history' => 'Tidak ada riwayat cedera besar, hanya beberapa bruise di tulang kering dari sparring.',
            'pain_location' => 'Lutut kanan (area medial & sedikit ke patellar tendon)',
                'pain_scale' => 5,
            'training_load' => 'Berat (sparring + pad work + conditioning)',
                'training_frequency' => '6x/minggu, 2–2.5 jam per sesi',
                'notes' => 'Hindari sparring, checking, dan teep power selama 7 hari pertama terapi.
Boleh lakukan shadowboxing & teknik non-impact.
Evaluasi tracking patella minggu ke-2 untuk mencegah overuse injury berulang.',
                'report_file_path' => 'health-reports/01KC0NZF0C9J2SDGHSKM7ZY6DN.pdf',
                'created_at' => '2025-12-09 04:30:09',
                'updated_at' => '2025-12-09 04:30:12',
            ),
            4 => 
            array (
                'screening_id' => 'SCR0005',
                'auto_increment' => 5,
                'athlete_id' => 'ATH0005',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:32:13',
                'blood_pressure' => '106/70',
                'heart_rate' => 79,
                'temperature' => '36.7',
                'respiration_rate' => 17,
                'oxygen_saturation' => 98,
            'chief_complaint' => 'Nyeri pada lutut depan (patella) terutama setelah melakukan lunging cepat. Nyeri makin terasa saat squat atau saat bangun dari posisi rendah.',
                'injury_history' => 'Pernah mengalami ketegangan ringan pada quadriceps 2 bulan lalu, tapi sudah pulih.',
            'pain_location' => 'Lutut kanan (patellofemoral region)',
                'pain_scale' => 4,
            'training_load' => 'Sedang–berat (kombinasi teknik, footwork & sparring)',
                'training_frequency' => '5–6x/minggu, durasi 2 jam',
                'notes' => 'Hindari lunging eksplosif selama 1–2 minggu.
Prioritaskan latihan footwork ringan & teknik garis.
Koreksi pola lutut saat lunge karena terlihat sedikit inward tracking.',
                'report_file_path' => 'health-reports/01KC0P34N9PBH1JXDS02JNRVP8.pdf',
                'created_at' => '2025-12-09 04:32:10',
                'updated_at' => '2025-12-09 04:32:13',
            ),
            5 => 
            array (
                'screening_id' => 'SCR0006',
                'auto_increment' => 6,
                'athlete_id' => 'ATH0006',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:34:20',
                'blood_pressure' => '107/72',
                'heart_rate' => 82,
                'temperature' => '36.8',
                'respiration_rate' => 18,
                'oxygen_saturation' => 98,
                'chief_complaint' => 'Nyeri pada pergelangan kaki kanan setelah mendarat tidak stabil saat latihan rebound. Terasa sakit saat melakukan cutting atau berlari cepat.',
                'injury_history' => 'Tidak ada riwayat ankle sprain besar, hanya pernah memar ringan 4 bulan lalu.',
                'pain_location' => 'Lateral ankle kanan',
                'pain_scale' => 5,
            'training_load' => 'Berat (sprint, stamina, scrimmage)',
                'training_frequency' => '5–6x/minggu, ±2 jam per sesi',
                'notes' => 'Hindari latihan yang melibatkan sprint dan cutting keras selama 1 minggu.
Boleh latihan shooting statis & passing drill.
Lakukan proprioception test di minggu ke-2 untuk lihat stabilitas ankle.',
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:34:18',
                'updated_at' => '2025-12-09 04:34:20',
            ),
            6 => 
            array (
                'screening_id' => 'SCR0007',
                'auto_increment' => 7,
                'athlete_id' => 'ATH0007',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:36:20',
                'blood_pressure' => '128/82',
                'heart_rate' => 85,
                'temperature' => '36.7',
                'respiration_rate' => 18,
                'oxygen_saturation' => 98,
            'chief_complaint' => 'Nyeri pergelangan tangan kanan dan kaku pada lengan bawah setelah scrimming panjang (6–7 jam). Makin terasa saat flicking cepat atau saat latihan aim.',
                'injury_history' => 'Tendinitis ringan 1 tahun lalu, sempat terapi 3 minggu. Balik kambuh saat workload meningkat.',
                'pain_location' => 'Wrist kanan → flexor tendon area',
                'pain_scale' => 6,
                'training_load' => 'Postur duduk: forward-leaning, sering tanpa break  Mouse usage: high-DPI, repetitive action',
                'training_frequency' => '6–9 jam/hari, kombinasi scrim + VOD review',
                'notes' => 'Disarankan memakai wrist rest, angle mouse lebih rendah, dan break tiap 45 menit.
Lakukan stretching forearm 3x sehari.
Evaluasi nerve gliding response di minggu kedua.',
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:36:18',
                'updated_at' => '2025-12-09 04:36:20',
            ),
            7 => 
            array (
                'screening_id' => 'SCR0008',
                'auto_increment' => 8,
                'athlete_id' => 'ATH0008',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:38:22',
                'blood_pressure' => '118/76',
                'heart_rate' => 80,
                'temperature' => '36.7',
                'respiration_rate' => 18,
                'oxygen_saturation' => 98,
                'chief_complaint' => 'Nyeri di bawah tempurung lutut kanan setelah latihan jumping & fast break drill. Terasa saat mendarat dan saat acceleration.',
                'injury_history' => 'Pernah mengalami “jumper’s knee” ringan 5 bulan lalu, pulih tapi tidak menjalani program penguatan secara penuh.',
            'pain_location' => 'Patellar tendon (lutut kanan bagian bawah)',
                'pain_scale' => 5,
            'training_load' => 'Berat (jump training, sprint, scrimmage)',
                'training_frequency' => '5–6x/minggu, ±2 jam',
                'notes' => 'Hindari latihan eksplosif seperti jumping & sprinting selama minggu pertama terapi.
Boleh latihan shooting statis dan passing drill.
Evaluasi tracking lutut (knee valgus) di minggu ke-2.',
                'report_file_path' => 'health-reports/01KC0PECPCWFMW7WP7SBEWR660.pdf',
                'created_at' => '2025-12-09 04:38:19',
                'updated_at' => '2025-12-09 04:38:22',
            ),
            8 => 
            array (
                'screening_id' => 'SCR0009',
                'auto_increment' => 9,
                'athlete_id' => 'ATH0009',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'routine',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:41:59',
                'blood_pressure' => '104/68',
                'heart_rate' => 77,
                'temperature' => '36.7',
                'respiration_rate' => 17,
                'oxygen_saturation' => 99,
            'chief_complaint' => 'Nyeri di bahu kiri (drawing side) setelah latihan intens 4 hari berturut-turut. Nyeri muncul saat menarik busur atau mengangkat lengan.',
                'injury_history' => 'Pernah mengalami tegang otot bahu ringan tahun lalu, sembuh tanpa terapi panjang.',
            'pain_location' => 'Area rotator cuff (supraspinatus & deltoid posterior)',
                'pain_scale' => 4,
                'training_load' => 'Intensitas: Repetisi 200–300 arrow/day  Postur: Dominan statis + shoulder loading',
                'training_frequency' => '3–4 jam/hari',
                'notes' => 'Hindari latihan >150 arrow/day sampai minggu pertama terapi selesai.
Fokus ke teknik drawing pelan, bukan power.
Perhatikan scapular retraction saat draw — terlihat sedikit tidak stabil.',
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:41:57',
                'updated_at' => '2025-12-09 04:41:59',
            ),
            9 => 
            array (
                'screening_id' => 'SCR0010',
                'auto_increment' => 10,
                'athlete_id' => 'ATH0010',
                'follow_up_therapy_schedule_id' => NULL,
                'screening_date' => '2025-12-09',
                'exam_type' => 'injury',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:44:08',
                'blood_pressure' => '112/74',
                'heart_rate' => 83,
                'temperature' => '36.8',
                'respiration_rate' => 18,
                'oxygen_saturation' => 98,
            'chief_complaint' => 'Nyeri pada bagian belakang paha kanan (hamstring) setelah sprint acceleration pada sesi latihan kemarin. Nyeri muncul lagi saat mencoba sprint di pemanasan.',
                'injury_history' => 'Tidak ada cedera besar sebelumnya, hanya tight hamstring beberapa kali.',
            'pain_location' => 'Hamstring kanan (biceps femoris area)',
                'pain_scale' => 5,
                'training_load' => 'Sprint drill, passing, small-sided games',
                'training_frequency' => '6x/minggu, 2 jam/sesi',
                'notes' => 'Tidak boleh sprint atau explosive movement selama 1 minggu.
Boleh jogging ringan jika tidak menambah nyeri.
Sprint progression dimulai minggu ke-2 (50% → 70% → 90%).',
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:44:05',
                'updated_at' => '2025-12-09 04:44:08',
            ),
            10 => 
            array (
                'screening_id' => 'SCR0011',
                'auto_increment' => 11,
                'athlete_id' => 'ATH0001',
                'follow_up_therapy_schedule_id' => 2,
                'screening_date' => '2025-12-09',
                'exam_type' => 'follow_up',
                'screening_result' => 'fit',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:45:23',
                'blood_pressure' => NULL,
                'heart_rate' => NULL,
                'temperature' => NULL,
                'respiration_rate' => NULL,
                'oxygen_saturation' => NULL,
                'chief_complaint' => NULL,
                'injury_history' => NULL,
                'pain_location' => NULL,
                'pain_scale' => NULL,
                'training_load' => NULL,
                'training_frequency' => NULL,
                'notes' => NULL,
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:45:20',
                'updated_at' => '2025-12-09 04:45:23',
            ),
            11 => 
            array (
                'screening_id' => 'SCR0012',
                'auto_increment' => 12,
                'athlete_id' => 'ATH0005',
                'follow_up_therapy_schedule_id' => 5,
                'screening_date' => '2025-12-09',
                'exam_type' => 'follow_up',
                'screening_result' => 'restricted',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:45:58',
                'blood_pressure' => NULL,
                'heart_rate' => NULL,
                'temperature' => NULL,
                'respiration_rate' => NULL,
                'oxygen_saturation' => NULL,
                'chief_complaint' => NULL,
                'injury_history' => NULL,
                'pain_location' => NULL,
                'pain_scale' => NULL,
                'training_load' => NULL,
                'training_frequency' => NULL,
                'notes' => NULL,
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:45:55',
                'updated_at' => '2025-12-09 04:45:58',
            ),
            12 => 
            array (
                'screening_id' => 'SCR0013',
                'auto_increment' => 13,
                'athlete_id' => 'ATH0002',
                'follow_up_therapy_schedule_id' => 1,
                'screening_date' => '2025-12-09',
                'exam_type' => 'follow_up',
                'screening_result' => 'restricted',
                'is_locked' => 1,
                'finalized_at' => '2025-12-09 04:46:57',
                'blood_pressure' => NULL,
                'heart_rate' => NULL,
                'temperature' => NULL,
                'respiration_rate' => NULL,
                'oxygen_saturation' => NULL,
                'chief_complaint' => NULL,
                'injury_history' => NULL,
                'pain_location' => NULL,
                'pain_scale' => NULL,
                'training_load' => NULL,
                'training_frequency' => NULL,
                'notes' => NULL,
                'report_file_path' => NULL,
                'created_at' => '2025-12-09 04:46:55',
                'updated_at' => '2025-12-09 04:46:57',
            ),
            13 => 
            array (
                'screening_id' => 'SCR0014',
                'auto_increment' => 14,
                'athlete_id' => 'ATH0006',
                'follow_up_therapy_schedule_id' => 6,
                'screening_date' => '2025-12-13',
                'exam_type' => 'follow_up',
                'screening_result' => 'active_therapy',
                'is_locked' => 1,
                'finalized_at' => '2025-12-13 08:38:04',
                'blood_pressure' => NULL,
                'heart_rate' => NULL,
                'temperature' => NULL,
                'respiration_rate' => NULL,
                'oxygen_saturation' => NULL,
                'chief_complaint' => NULL,
                'injury_history' => NULL,
                'pain_location' => NULL,
                'pain_scale' => NULL,
                'training_load' => NULL,
                'training_frequency' => NULL,
                'notes' => NULL,
                'report_file_path' => NULL,
                'created_at' => '2025-12-13 08:37:56',
                'updated_at' => '2025-12-13 08:38:04',
            ),
            14 => 
            array (
                'screening_id' => 'SCR0015',
                'auto_increment' => 15,
                'athlete_id' => 'ATH0004',
                'follow_up_therapy_schedule_id' => 4,
                'screening_date' => '2025-12-13',
                'exam_type' => 'follow_up',
                'screening_result' => 'fit',
                'is_locked' => 1,
                'finalized_at' => '2025-12-13 08:40:36',
                'blood_pressure' => NULL,
                'heart_rate' => NULL,
                'temperature' => NULL,
                'respiration_rate' => NULL,
                'oxygen_saturation' => NULL,
                'chief_complaint' => NULL,
                'injury_history' => NULL,
                'pain_location' => NULL,
                'pain_scale' => NULL,
                'training_load' => NULL,
                'training_frequency' => NULL,
                'notes' => NULL,
                'report_file_path' => NULL,
                'created_at' => '2025-12-13 08:40:30',
                'updated_at' => '2025-12-13 08:40:36',
            ),
        ));
        
        
    }
}