<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TrainingSessionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('training_sessions')->delete();
        
        \DB::table('training_sessions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'program_id' => 'TPR0001',
                'date' => '2025-01-05',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Qui saepe fugit nobis quos ullam placeat ipsam officia sed tempore quos.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            1 => 
            array (
                'id' => 2,
                'program_id' => 'TPR0001',
                'date' => '2025-01-12',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Modi iusto est sit qui pariatur officia.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            2 => 
            array (
                'id' => 3,
                'program_id' => 'TPR0001',
                'date' => '2025-01-19',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Quia sapiente aut assumenda velit quae exercitationem voluptas.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            3 => 
            array (
                'id' => 4,
                'program_id' => 'TPR0001',
                'date' => '2025-01-26',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Tenetur sed corporis inventore reiciendis dolorem necessitatibus inventore officiis nihil tenetur ad voluptatum quam.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            4 => 
            array (
                'id' => 5,
                'program_id' => 'TPR0001',
                'date' => '2025-02-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Enim natus quis harum recusandae accusamus quisquam officia non hic accusantium eligendi quidem.',
                'status' => 'cancelled',
                'cancel_reason' => 'Pelatih berhalangan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            5 => 
            array (
                'id' => 6,
                'program_id' => 'TPR0002',
                'date' => '2025-01-10',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Maiores dolore occaecati fugit vel delectus et error odit culpa.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            6 => 
            array (
                'id' => 7,
                'program_id' => 'TPR0002',
                'date' => '2025-01-12',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Est iste aliquam cupiditate similique vel enim perferendis officia sed aut enim sit ipsam.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            7 => 
            array (
                'id' => 8,
                'program_id' => 'TPR0002',
                'date' => '2025-01-14',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Omnis ab odit totam quia harum reprehenderit perspiciatis officiis provident.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            8 => 
            array (
                'id' => 9,
                'program_id' => 'TPR0002',
                'date' => '2025-01-16',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Est aut maxime rerum nobis ducimus illum voluptas aut magnam.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            9 => 
            array (
                'id' => 10,
                'program_id' => 'TPR0002',
                'date' => '2025-01-18',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Illo cumque dolorum sed qui dolor aut incidunt consequatur.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            10 => 
            array (
                'id' => 11,
                'program_id' => 'TPR0002',
                'date' => '2025-01-20',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Id architecto est cumque sit hic nesciunt possimus et.',
                'status' => 'cancelled',
                'cancel_reason' => 'Kondisi atlet tidak memungkinkan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            11 => 
            array (
                'id' => 12,
                'program_id' => 'TPR0003',
                'date' => '2025-02-01',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Officiis et pariatur aspernatur enim eos dolorem eius omnis dicta ratione rerum.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            12 => 
            array (
                'id' => 13,
                'program_id' => 'TPR0003',
                'date' => '2025-02-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Molestias nam est qui ut occaecati voluptates voluptas molestiae accusamus.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            13 => 
            array (
                'id' => 14,
                'program_id' => 'TPR0003',
                'date' => '2025-02-03',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Minima alias totam voluptas totam maxime veniam ipsam aliquam porro autem alias repudiandae.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            14 => 
            array (
                'id' => 15,
                'program_id' => 'TPR0003',
                'date' => '2025-02-04',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Autem doloribus optio voluptate hic alias et.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            15 => 
            array (
                'id' => 16,
                'program_id' => 'TPR0003',
                'date' => '2025-02-05',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Velit rerum omnis quas laudantium ut qui quis.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            16 => 
            array (
                'id' => 17,
                'program_id' => 'TPR0003',
                'date' => '2025-02-06',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'In minus fugit natus natus sunt quasi.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            17 => 
            array (
                'id' => 18,
                'program_id' => 'TPR0003',
                'date' => '2025-02-07',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Perspiciatis architecto numquam consequatur dignissimos omnis eius nemo ad et ab.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            18 => 
            array (
                'id' => 19,
                'program_id' => 'TPR0003',
                'date' => '2025-02-08',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Incidunt necessitatibus voluptatem accusantium omnis voluptatem et vero deserunt.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            19 => 
            array (
                'id' => 20,
                'program_id' => 'TPR0003',
                'date' => '2025-02-09',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Sunt distinctio et voluptas et vitae omnis in voluptatum.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            20 => 
            array (
                'id' => 21,
                'program_id' => 'TPR0003',
                'date' => '2025-02-10',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Enim at in molestias quam explicabo soluta in.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            21 => 
            array (
                'id' => 22,
                'program_id' => 'TPR0003',
                'date' => '2025-02-11',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Reiciendis dignissimos in dolor est ratione dolorem expedita veritatis et.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            22 => 
            array (
                'id' => 23,
                'program_id' => 'TPR0003',
                'date' => '2025-02-12',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Nisi laboriosam vel neque ut minima rem explicabo alias numquam provident pariatur minus dolores.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            23 => 
            array (
                'id' => 24,
                'program_id' => 'TPR0004',
                'date' => '2025-01-15',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Reprehenderit quas nam facere maxime itaque quidem recusandae vitae blanditiis aut nesciunt.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            24 => 
            array (
                'id' => 25,
                'program_id' => 'TPR0004',
                'date' => '2025-01-18',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Omnis dolorem aut quasi et magni quam.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            25 => 
            array (
                'id' => 26,
                'program_id' => 'TPR0004',
                'date' => '2025-01-21',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Enim suscipit nam laborum nobis occaecati nobis atque provident.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            26 => 
            array (
                'id' => 27,
                'program_id' => 'TPR0004',
                'date' => '2025-01-24',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Tempore nam aliquam laborum ipsam fugit sunt nemo in odit.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            27 => 
            array (
                'id' => 28,
                'program_id' => 'TPR0004',
                'date' => '2025-01-27',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Reiciendis quia minima facilis amet nihil id.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            28 => 
            array (
                'id' => 29,
                'program_id' => 'TPR0004',
                'date' => '2025-01-30',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Enim non tempore qui ex ut dolor laudantium tenetur distinctio soluta.',
                'status' => 'cancelled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            29 => 
            array (
                'id' => 30,
                'program_id' => 'TPR0004',
                'date' => '2025-02-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Dolores laudantium dolorem nihil eos voluptas sit eum est.',
                'status' => 'cancelled',
                'cancel_reason' => 'Pelatih berhalangan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            30 => 
            array (
                'id' => 31,
                'program_id' => 'TPR0004',
                'date' => '2025-02-05',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Dolore nam ea autem voluptatem ipsa nobis.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            31 => 
            array (
                'id' => 32,
                'program_id' => 'TPR0005',
                'date' => '2025-01-08',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Distinctio perspiciatis hic necessitatibus cum magni sint voluptatibus natus labore.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            32 => 
            array (
                'id' => 33,
                'program_id' => 'TPR0005',
                'date' => '2025-01-11',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Reprehenderit recusandae enim facilis nemo exercitationem laborum eius minima sapiente aut aut.',
                'status' => 'cancelled',
                'cancel_reason' => 'Kondisi atlet tidak memungkinkan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            33 => 
            array (
                'id' => 34,
                'program_id' => 'TPR0005',
                'date' => '2025-01-14',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Numquam ut et corporis corporis laboriosam nobis repudiandae recusandae suscipit placeat id nam natus.',
                'status' => 'cancelled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            34 => 
            array (
                'id' => 35,
                'program_id' => 'TPR0005',
                'date' => '2025-01-17',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Dolores laudantium omnis dolores quae sunt in quas exercitationem perferendis perspiciatis consequatur asperiores quia nihil.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            35 => 
            array (
                'id' => 36,
                'program_id' => 'TPR0005',
                'date' => '2025-01-20',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Numquam facere ratione reiciendis enim tenetur inventore laboriosam vero est rerum sint at sapiente.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            36 => 
            array (
                'id' => 37,
                'program_id' => 'TPR0005',
                'date' => '2025-01-23',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Maiores hic est veritatis consequatur culpa labore saepe suscipit odio.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            37 => 
            array (
                'id' => 38,
                'program_id' => 'TPR0005',
                'date' => '2025-01-26',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Iure dolorum voluptatibus numquam delectus repellat assumenda laborum sunt quasi sed.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            38 => 
            array (
                'id' => 39,
                'program_id' => 'TPR0005',
                'date' => '2025-01-29',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Aliquid officiis dolorem alias sunt enim voluptatem qui odio.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            39 => 
            array (
                'id' => 40,
                'program_id' => 'TPR0005',
                'date' => '2025-02-01',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Beatae dolorem totam qui qui veniam modi ipsa saepe quibusdam architecto illum qui.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            40 => 
            array (
                'id' => 41,
                'program_id' => 'TPR0005',
                'date' => '2025-02-04',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Qui id modi eum cum consequatur quia qui quaerat iste iure beatae.',
                'status' => 'cancelled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            41 => 
            array (
                'id' => 42,
                'program_id' => 'TPR0006',
                'date' => '2025-01-20',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Non quis aut dolorum autem sed est rerum.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            42 => 
            array (
                'id' => 43,
                'program_id' => 'TPR0006',
                'date' => '2025-01-21',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Culpa vitae voluptatum dolor doloremque qui esse nihil cupiditate quidem illo saepe nihil.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            43 => 
            array (
                'id' => 44,
                'program_id' => 'TPR0006',
                'date' => '2025-01-22',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Ut similique harum id quasi odit optio consequatur.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            44 => 
            array (
                'id' => 45,
                'program_id' => 'TPR0006',
                'date' => '2025-01-23',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Enim voluptatem laborum iusto aut ea tempora sunt quia id.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            45 => 
            array (
                'id' => 46,
                'program_id' => 'TPR0006',
                'date' => '2025-01-24',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Sed neque vel dolores cupiditate delectus impedit qui nihil dolorem numquam voluptatem qui corporis.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            46 => 
            array (
                'id' => 47,
                'program_id' => 'TPR0006',
                'date' => '2025-01-25',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Possimus deserunt sed laudantium ut omnis autem at quisquam qui ea ipsam dolores possimus labore.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            47 => 
            array (
                'id' => 48,
                'program_id' => 'TPR0006',
                'date' => '2025-01-26',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Soluta dolor similique illum doloribus iste voluptas.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            48 => 
            array (
                'id' => 49,
                'program_id' => 'TPR0006',
                'date' => '2025-01-27',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Autem voluptatibus tempore rerum aliquid explicabo fuga ut sint culpa.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            49 => 
            array (
                'id' => 50,
                'program_id' => 'TPR0006',
                'date' => '2025-01-28',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Aspernatur temporibus saepe repellendus enim enim suscipit et alias ratione pariatur rerum commodi.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            50 => 
            array (
                'id' => 51,
                'program_id' => 'TPR0006',
                'date' => '2025-01-29',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Qui ipsa pariatur tempore quia sit omnis mollitia quidem.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            51 => 
            array (
                'id' => 52,
                'program_id' => 'TPR0006',
                'date' => '2025-01-30',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Repellendus quo omnis reprehenderit temporibus id asperiores labore.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            52 => 
            array (
                'id' => 53,
                'program_id' => 'TPR0006',
                'date' => '2025-01-31',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Et quibusdam facere omnis quas quos fugiat ut saepe reiciendis labore vel sit delectus.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            53 => 
            array (
                'id' => 54,
                'program_id' => 'TPR0006',
                'date' => '2025-02-01',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Animi provident asperiores cupiditate in reiciendis corporis tempora ipsam quos qui maxime ex.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            54 => 
            array (
                'id' => 55,
                'program_id' => 'TPR0006',
                'date' => '2025-02-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Eum nulla voluptatum possimus suscipit magni id distinctio dicta sunt.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            55 => 
            array (
                'id' => 56,
                'program_id' => 'TPR0007',
                'date' => '2025-02-05',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Asperiores aperiam rerum eveniet ex velit blanditiis numquam cupiditate non.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            56 => 
            array (
                'id' => 57,
                'program_id' => 'TPR0007',
                'date' => '2025-02-10',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Reiciendis necessitatibus cum qui error quam necessitatibus repudiandae tenetur perspiciatis dolorem.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            57 => 
            array (
                'id' => 58,
                'program_id' => 'TPR0007',
                'date' => '2025-02-15',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Cumque dignissimos molestiae sed laborum ipsam id est est id libero quae.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            58 => 
            array (
                'id' => 59,
                'program_id' => 'TPR0007',
                'date' => '2025-02-20',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Quisquam dolor voluptas voluptatibus sit expedita dolores nesciunt corrupti similique.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            59 => 
            array (
                'id' => 60,
                'program_id' => 'TPR0007',
                'date' => '2025-02-25',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Consequuntur laboriosam tempore unde quis animi eos.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            60 => 
            array (
                'id' => 61,
                'program_id' => 'TPR0007',
                'date' => '2025-03-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Dolores saepe nam iure culpa inventore quidem.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            61 => 
            array (
                'id' => 62,
                'program_id' => 'TPR0008',
                'date' => '2025-01-28',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Iure itaque enim ea placeat pariatur id libero voluptas.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            62 => 
            array (
                'id' => 63,
                'program_id' => 'TPR0008',
                'date' => '2025-01-29',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Saepe voluptatem reprehenderit cumque minus laboriosam incidunt qui eveniet quam.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            63 => 
            array (
                'id' => 64,
                'program_id' => 'TPR0008',
                'date' => '2025-01-30',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Facilis velit qui tempore illo veritatis dolor praesentium mollitia vero eum qui nihil.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            64 => 
            array (
                'id' => 65,
                'program_id' => 'TPR0008',
                'date' => '2025-01-31',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Totam accusantium id magnam iste nobis consequuntur qui ut quas occaecati maxime.',
                'status' => 'cancelled',
                'cancel_reason' => 'Kondisi atlet tidak memungkinkan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            65 => 
            array (
                'id' => 66,
                'program_id' => 'TPR0008',
                'date' => '2025-02-01',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Nobis nihil quis autem veniam dolorem amet est qui dolor aut aliquid.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 12:31:32',
            ),
            66 => 
            array (
                'id' => 67,
                'program_id' => 'TPR0008',
                'date' => '2025-02-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Inventore necessitatibus vero aliquam quasi voluptatem natus cum voluptates eaque nulla.',
                'status' => 'scheduled',
                'cancel_reason' => 'Lapangan dipakai tim lain',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 12:31:37',
            ),
            67 => 
            array (
                'id' => 68,
                'program_id' => 'TPR0008',
                'date' => '2025-02-03',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Ad cum occaecati voluptatem dolores necessitatibus sed est.',
                'status' => 'scheduled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 12:31:41',
            ),
            68 => 
            array (
                'id' => 69,
                'program_id' => 'TPR0008',
                'date' => '2025-02-04',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Modi officia excepturi consequuntur voluptatem voluptas sed.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 12:31:46',
            ),
            69 => 
            array (
                'id' => 70,
                'program_id' => 'TPR0008',
                'date' => '2025-02-05',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Praesentium sint corporis aut voluptatem necessitatibus itaque rem est laborum harum omnis.',
                'status' => 'scheduled',
                'cancel_reason' => 'Pelatih berhalangan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 12:31:50',
            ),
            70 => 
            array (
                'id' => 71,
                'program_id' => 'TPR0008',
                'date' => '2025-02-06',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Eos quo dicta unde beatae cumque aut ipsa perferendis ducimus id quo rem.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 12:31:54',
            ),
            71 => 
            array (
                'id' => 72,
                'program_id' => 'TPR0008',
                'date' => '2025-02-07',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Unde id amet aspernatur modi voluptatum doloribus aliquid fuga vel placeat ea enim dolorem.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            72 => 
            array (
                'id' => 73,
                'program_id' => 'TPR0008',
                'date' => '2025-02-08',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Aperiam iure quasi perferendis ex praesentium est qui fuga earum non aut id vel.',
                'status' => 'cancelled',
                'cancel_reason' => 'Pelatih berhalangan',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            73 => 
            array (
                'id' => 74,
                'program_id' => 'TPR0008',
                'date' => '2025-02-09',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Dolores et maxime dolores adipisci nihil id animi veniam.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            74 => 
            array (
                'id' => 75,
                'program_id' => 'TPR0008',
                'date' => '2025-02-10',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Libero iste qui dolores consectetur aspernatur non.',
                'status' => 'cancelled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            75 => 
            array (
                'id' => 76,
                'program_id' => 'TPR0008',
                'date' => '2025-02-11',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Ut vitae dolorem ut corrupti nihil cupiditate laborum debitis.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            76 => 
            array (
                'id' => 77,
                'program_id' => 'TPR0008',
                'date' => '2025-02-12',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Corrupti laboriosam quia animi illo cumque voluptas soluta fugiat accusamus quibusdam magnam soluta voluptas.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            77 => 
            array (
                'id' => 78,
                'program_id' => 'TPR0009',
                'date' => '2025-01-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Consectetur odio neque quod quia mollitia repudiandae.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            78 => 
            array (
                'id' => 79,
                'program_id' => 'TPR0009',
                'date' => '2025-01-05',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Exercitationem id dolores numquam nesciunt ea omnis harum itaque.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            79 => 
            array (
                'id' => 80,
                'program_id' => 'TPR0009',
                'date' => '2025-01-08',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Cumque sed velit vel dolore inventore adipisci alias veniam facilis saepe.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            80 => 
            array (
                'id' => 81,
                'program_id' => 'TPR0009',
                'date' => '2025-01-11',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Labore eum similique quo et debitis dolor officiis itaque.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            81 => 
            array (
                'id' => 82,
                'program_id' => 'TPR0009',
                'date' => '2025-01-14',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Sit iure atque provident minus consequatur cum in modi.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            82 => 
            array (
                'id' => 83,
                'program_id' => 'TPR0010',
                'date' => '2025-01-12',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Omnis voluptas neque ut et ut accusantium.',
                'status' => 'completed',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            83 => 
            array (
                'id' => 84,
                'program_id' => 'TPR0010',
                'date' => '2025-01-15',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Samping',
                'activities_notes' => 'Quas nemo nobis aut omnis commodi iste iure et quia.',
                'status' => 'on_going',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            84 => 
            array (
                'id' => 85,
                'program_id' => 'TPR0010',
                'date' => '2025-01-18',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Ruang Latihan Fisik',
                'activities_notes' => 'Explicabo sint et et voluptates voluptates dolorem ipsam porro sequi iusto nisi.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:09:10',
            ),
            85 => 
            array (
                'id' => 86,
                'program_id' => 'TPR0010',
                'date' => '2025-01-21',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Voluptates quo cumque dolores dolorem et quis sit nulla labore nisi est quo.',
                'status' => 'scheduled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:21:47',
            ),
            86 => 
            array (
                'id' => 87,
                'program_id' => 'TPR0010',
                'date' => '2025-01-24',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Nulla voluptas debitis voluptatibus nihil asperiores in dolores aut deleniti culpa nulla dolorem a.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:21:54',
            ),
            87 => 
            array (
                'id' => 88,
                'program_id' => 'TPR0010',
                'date' => '2025-01-27',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Lapangan Utama',
                'activities_notes' => 'Mollitia ab ducimus recusandae nihil incidunt odit distinctio.',
                'status' => 'scheduled',
                'cancel_reason' => 'Hujan deras',
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:22:02',
            ),
            88 => 
            array (
                'id' => 89,
                'program_id' => 'TPR0010',
                'date' => '2025-01-30',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Vitae saepe magni eos aliquid ipsa praesentium.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:22:09',
            ),
            89 => 
            array (
                'id' => 90,
                'program_id' => 'TPR0010',
                'date' => '2025-02-02',
                'start_time' => '08:00:00',
                'end_time' => '10:00:00',
                'duration_minutes' => 120,
                'location' => 'Gym Indoor',
                'activities_notes' => 'Rem sit exercitationem omnis incidunt dolorum ea dolorum aspernatur sed et.',
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-08 11:09:10',
                'updated_at' => '2025-12-08 11:22:14',
            ),
            90 => 
            array (
                'id' => 91,
                'program_id' => 'TPR0010',
                'date' => '2025-12-13',
                'start_time' => '07:45:00',
                'end_time' => '08:45:00',
                'duration_minutes' => 60,
                'location' => 'Bandung, Indonesia',
                'activities_notes' => NULL,
                'status' => 'scheduled',
                'cancel_reason' => NULL,
                'created_at' => '2025-12-12 20:42:56',
                'updated_at' => '2025-12-12 20:42:56',
            ),
        ));
        
        
    }
}